targets:
  $default:
    builders:
      json_serializable:
        options:
          create_to_json: false
          field_rename: snake
      stacked_generator|stackedRouterGenerator:
        options:
          navigator2: true
