name: nowu
description: now-u App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.6+56
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  share: ^2.0.4
  uuid: ^4.3.3

  stacked: ^3.4.2
  stacked_services: ^1.4.0

  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.2.5
  open_mail_app: ^0.4.5
  android_intent: ^2.0.2
  tuple: ^2.0.2
  smooth_page_indicator: ^1.1.0
  rect_getter: ^1.1.0
  permission_handler: ^11.3.0
  time: ^2.1.4
  #  TODO: Update with Flutter
  intl: ^0.18.1
  flutter_markdown: ^0.6.20+1
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6

  flutter_secure_storage: ^9.0.0
  flutter_inappwebview: ^6.0.0
  uni_links: ^0.5.1
  device_info: ^2.0.2
  
  # Firebase
  firebase_analytics: ^10.8.6
  firebase_crashlytics: ^3.4.15
  firebase_messaging: ^14.7.16
  firebase_dynamic_links: ^5.4.14
  firebase_remote_config: ^4.3.14
  firebase_core: ^2.25.4

  dio: ^5.4.1
  faker: ^2.0.0

  #  TODO: Update with Flutter
  supabase_flutter: ^1.10.25
  meilisearch: ^0.15.0
  google_sign_in: ^6.2.1

  sentry_flutter: ^7.16.1
  sentry_logging: ^7.16.1
  sentry_dio: ^7.16.1
  logging: ^1.2.0

  causeApiClient:
    path: openapi/causeApi

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  flutter_launcher_icons: ^0.13.1
  dartdoc: ^8.0.5
  build_runner: ^2.4.8
  stacked_generator: ^1.6.0

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon-ios.jpg"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
   - assets/imgs/
   - assets/imgs/intro/
   - assets/imgs/badges/
   - assets/imgs/sdg/
   - assets/imgs/graphics/
   - assets/imgs/actions/
   - assets/json/
   - assets/ca/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Black.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
        - asset: assets/fonts/Raleway-ExtraBold.ttf
        - asset: assets/fonts/Raleway-SemiBold.ttf
        - asset: assets/fonts/Raleway-Medium.ttf
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway-ExtraLight.ttf
        - asset: assets/fonts/Raleway-Thin.ttf
    - family: PeaceSans
      fonts:
        - asset: assets/fonts/peace_sans.otf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-Black.ttf
          weight: 800
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 500
    - family: SourceSans
      fonts:
        - asset: assets/fonts/SourceSansPro/SourceSansPro-Italic.ttf
          weight: 400
          style: italic
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/Icons/CustomIcons.ttf
    - family: CustomIcons2
      fonts:
        - asset: assets/fonts/Icons/CustomIcons2.ttf
    - family: CustomIconsClipboard
      fonts:
        - asset: assets/fonts/Icons/CustomIconsClipboard.ttf
    - family: CauseIcons
      fonts:
        - asset: assets/fonts/Icons/CauseIcons.ttf

flutter_intl:
  enabled: true
