name: app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0-dev+43

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  share: ^2.0.4
  uuid: ^3.0.5

  stacked: ^2.3.6

  shared_preferences: ^2.0.8
  path_provider: ^2.0.5
  font_awesome_flutter: ^9.1.0
  url_launcher: ^6.0.12
  android_intent: ^2.0.2
  tuple: ^2.0.0
  smooth_page_indicator: ^1.0.0+2
  rect_getter: ^1.0.0
  permission_handler: ^10.1.0
  time: ^2.0.0
  intl: ^0.17.0 # Date formatting
  flutter_markdown: ^0.6.7
  cached_network_image: ^3.2.1
  equatable: ^2.0.3
  
  rflutter_alert: ^2.0.4

  get_it: ^7.2.0
  get: ^4.3.8 # do things without context

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

  flutter_secure_storage: ">=4.2.1 <8.0.0"
  flutter_inappwebview: 5.4.4+3 
  uni_links: ^0.5.1
  device_info: ^2.0.2
  
  # Firebase
  firebase_analytics: ^10.0.3
  firebase_crashlytics: ^3.0.3
  firebase_messaging: ^14.0.3
  firebase_dynamic_links: ^5.0.3
  firebase_remote_config: ^3.0.3
  firebase_core: ^2.1.1
  collection: ^1.15.0-nullsafety.4
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0
  faker: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.15
  mocktail: ^0.3.0
  flutter_launcher_icons: ^0.9.2
  flutter_redux_dev_tools: ^0.5.1
  dartdoc: ^6.0.0
  build_runner: ^2.1.4


flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon-ios.jpg"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/imgs/
   - assets/imgs/intro/
   - assets/imgs/badges/
   - assets/imgs/sdg/
   - assets/imgs/graphics/
   - assets/json/
   - assets/ca/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Black.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
        - asset: assets/fonts/Raleway-ExtraBold.ttf
        - asset: assets/fonts/Raleway-SemiBold.ttf
        - asset: assets/fonts/Raleway-Medium.ttf
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway-ExtraLight.ttf
        - asset: assets/fonts/Raleway-Thin.ttf
    - family: PeaceSans
      fonts:
        - asset: assets/fonts/peace_sans.otf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-Black.ttf
          weight: 800
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 500
    - family: SourceSans
      fonts:
        - asset: assets/fonts/SourceSansPro/SourceSansPro-Italic.ttf
          weight: 400
          style: italic
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/Icons/CustomIcons.ttf
    - family: CustomIcons2
      fonts:
        - asset: assets/fonts/Icons/CustomIcons2.ttf
    - family: CustomIconsClipboard
      fonts:
        - asset: assets/fonts/Icons/CustomIconsClipboard.ttf

  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
