name: 'Setup app'
description: 'Install flutter and dependencies'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - name: Setup docker
      if: runner.os == 'macos'
      shell: bash
      run: |
        brew install colima
        colima delete 
        colima start

    # Setup the flutter environment.
    - name: Setup flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # 'dev', 'alpha', default to: 'stable'
        flutter-version: '3.22.3'
        cache: true

    - name: Flutter version
      shell: bash
      run: |
        dart --version
        flutter --version

    - name: Generate openapi client
      shell: bash
      run: cd openapi && make generate-prod && dart format .

    # Install your project's dependencies
    - name: Install dependencies
      shell: bash
      run: flutter pub get

    - name: Run build runner
      shell: bash
      run: flutter pub run build_runner build --delete-conflicting-outputs
