name: 'Setup app'
description: 'Install flutter and dependencies'

inputs:
  checkout-token:
    description: 'Token used to checkout app and font repos'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        token: ${{ inputs.checkout-token }}

    - name: Install openapi generator
      shell: bash
      run: |
        npm install @openapitools/openapi-generator-cli -g

    # Setup the flutter environment.
    - name: Setup flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # 'dev', 'alpha', default to: 'stable'
        flutter-version: '3.24.3'
        cache: true

    - name: Flutter version
      shell: bash
      run: |
        dart --version
        flutter --version

    - name: Generate openapi client
      shell: bash
      run: cd openapi && make generate-prod && dart format .

    # Install your project's dependencies
    - name: Install dependencies
      shell: bash
      run: flutter pub get

    - name: Run build runner
      shell: bash
      run: flutter pub run build_runner build --delete-conflicting-outputs
