name: Android release

on:
  workflow_dispatch:

# TODO Use tag to set version in setup app
# on:
#   workflow_call:
#     inputs:
#       version:
#         required: true
#         type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  release_android:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2

    - name: 🧰 Setup app
      uses: ./.github/actions/setup-app

    - name: 🔑 Add secrets
      env:
        KEY_PROPERTIES_BASE64: ${{ secrets.KEY_PROPERTIES_BASE64 }}
        KEY_JKS_BASE64: ${{ secrets.KEY_JKS_BASE64 }}
      run: |
        echo $KEY_PROPERTIES_BASE64 | base64 -d > ./android/key.properties
        echo $KEY_JKS_BASE64 | base64 -d > ./android/app/key.jks

    - name: 🏴‍☠️ Java setup
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: 🛠️ Build app
      run: flutter build appbundle --release

    - name: ⏫ Upload bundle as gh artifact
      uses: actions/upload-artifact@v2
      with:
        name: Signed app bundle
        path: ${{steps.sign_app.outputs.signedReleaseFile}}

    - name: ⏫ Upload bundle to Play Store
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.ANDROID_SERVICE_ACCOUNT_JSON }}
        packageName: com.nowu.app
        releaseFiles: /home/runner/work/now-u-app/now-u-app/build/app/outputs/bundle/release/app-release.aab
        track: production
        status: completed
        # inAppUpdatePriority: 2
        # userFraction: 0.33
        # whatsNewDirectory: distribution/whatsnew
        # mappingFile: app/build/outputs/mapping/release/mapping.txt
