name: Flutter CI CD

# This workflow is triggered on pushes to the repository.

# TODO Trigger on tag
on:
  push: 
    # branches: [staging, master]
    branches: [staging]
  # pull_request:
  #  branches: [ dev ]
  workflow_dispatch: # to manually run this workflow
    
# on: push    # Default will running for every branch.
    

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Trigger other 2 actions
        run: echo TODO
