name: Flutter CI CD

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

  workflow_dispatch: # to manually run this workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  prepare:
    name: Release setup
    runs-on: macos-latest
    outputs:
      ref: ${{ steps.commit.outputs.commit_long_sha }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Extract version from tag
        uses: damienaicheh/extract-version-from-tag-action@v1.1.0

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # 'dev', 'alpha', default to: 'stable'
          flutter-version: '3.16.x'
          cache: true

      - name: Setup cider
        run: |
          export PATH="$PATH":"$HOME/.pub-cache/bin"
          flutter pub global activate cider

      - name: Set version
        run: |
          echo "Setting version to ${{ github.ref_name }}"
          cider version ${{ github.ref_name }}

      - name: Update change log
        run: cider release

      - id: commit
        name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          branch: main
          message: "Release ${{ github.ref_name }} - Updates version in pubspec.yaml & update change log"

  release-ios:
    name: Release IOS
    needs: prepare
    uses: now-u/now-u-app/.github/workflows/ios-release.yml@main
    secrets: inherit
    with:
      ref: ${{ needs.prepare.outputs.ref }}

  release-android:
    name: Release Android
    needs: prepare
    uses: now-u/now-u-app/.github/workflows/android-release.yml@main
    secrets: inherit
    with:
      ref: ${{ needs.prepare.outputs.ref }}
