name: Flutter tests

# Run this workflow every time a new commit pushed to your repository
on: pull_request

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      CHANGELOG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'

      - run: dart --version
      - run: flutter --version
      - run: flutter pub get
      
      - name: Linting 
        run: flutter format .

      - name: Commit linting 
      - uses: EndBug/add-and-commit@v7.0.0
        with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
     
      - name: Run tests
        run: flutter test
