name: Flutter CI CD

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

  workflow_dispatch: # to manually run this workflow
    inputs:
      version:
        description: 'Version number to release'
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    uses: now-u/now-u-app/.github/workflows/flutter-test.yml@main
    secrets: inherit

  get-version:
    name: Get version
    runs-on: ubuntu-latest
    outputs:
      build-name: ${{ steps.get-build-name.outputs.build-name }}
      build-number: ${{ steps.get-build-number.outputs.build-number }}
    env:
      TAG: ${{ github.event.inputs.version != '' && github.event.inputs.version || github.ref_name }}
    steps:
        - id: get-build-name
          run:  echo "build-name=${TAG%+*}" >> "$GITHUB_OUTPUT"
        - id: get-build-number
          run: echo "build-number=${TAG##*+}" >> "$GITHUB_OUTPUT"

  release-ios:
    name: Release IOS
    needs: [test, get-version]
    uses: now-u/now-u-app/.github/workflows/ios-release.yml@main
    secrets: inherit
    with:
      build-name: ${{ needs.get-version.outputs.build-name }}
      build-number: ${{ needs.get-version.outputs.build-number }}

  release-android:
    name: Release Android
    needs: [test, get-version]
    uses: now-u/now-u-app/.github/workflows/android-release.yml@main
    secrets: inherit
    with:
      build-name: ${{ needs.get-version.outputs.build-name }}
      build-number: ${{ needs.get-version.outputs.build-number }}
