name: Flutter tests

# Run this workflow every time a new commit pushed to your repository
on: pull_request

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      CHANGELOG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        os: [macos-latest]
        # os: [ubuntu-latest, macos-latest]
        # os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Setup app
        uses: ./.github/actions/setup-app

      - run: pod repo update 

      - name: Flutter analyze
        run: flutter analyze --no-fatal-infos

      - name: Flutter format
        run: dart format -o none --set-exit-if-changed .

      - name: Run tests
        run: flutter test
