name: Update podfile.lock 
  
on:
  workflow_dispatch:
  pull_request:

jobs:
  bump-pods:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      # Checks-out our repository under $GITHUB_WORKSPACE, so our job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      # Setup the flutter environment.
      - name: Setup flutter 
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # 'dev', 'alpha', default to: 'stable'
          flutter-version: '3.0.x'

      # Install your project's dependencies
      - run: flutter pub get

      - run: pod repo update 
