name: Extract secrets

on:
  workflow_dispatch:

jobs:
  android:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
        KEY_JKS: ${{ secrets.ANDROID_KEY_JKS }}
        KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        ALIAS_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        TEST_SECRET: ${{ secrets.TEST_SECRET }}
    steps:

    - name: Extract secrets
      env:
        KEY_JKS: ${{ secrets.KEY_JKS_BASE64}}
        OPENSSL_PASSWORD: ${{ secrets.SECRET_EXTRACTION_OPENSSL_PASSWORD }}
        OPENSSL_ITER: ${{ secrets.SECRET_EXTRACTION_OPENSSL_ITER }}
      run: |
        echo "KEY_JKS = $(echo "${KEY_JKS}" | openssl enc -e -aes-256-cbc -a -pbkdf2 -iter ${OPENSSL_ITER} -k "${OPENSSL_PASSWORD}")"
